- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present

- name: Deploy Nginx configuration file
  template:
    src: "{{ nginx_config_file }}"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Nginx

- name: Ensure Nginx static directory exists
  file:
    path: "{{ nginx_static_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
