---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
    update_cache: yes  # Met à jour le cache APT avant installation

- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Wait for Nginx to be ready on port 80
  wait_for:
    host: "52.166.232.202"  # Adresse IP de la machine cible
    port: 80
    state: started
    delay: 10
    timeout: 30  # Timeout après 30 secondes si le service ne répond pas
