- name: Wait for Keycloak to be ready
  wait_for:
    host: localhost
    port: 8080
    state: started
    delay: 10

- name: Run Nginx container with Keycloak authentication
  docker_container:
    name: nginx
    image: nginx:latest
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
    environment:
      KEYCLOAK_URL: "http://keycloak:8080/auth"
      KEYCLOAK_REALM: "myrealm"
      CLIENT_ID: "nginx-client"
      CLIENT_SECRET: "nginx-secret"
    networks:
      - keycloak_network
