---
- name: Wait for PostgreSQL to be ready
  wait_for:
    host: "52.166.232.202"
    port: 5432
    state: started
    delay: 10

- name: Configure Keycloak DB container
  docker_container:
    name: keycloak
    image: jboss/keycloak:latest
    env:
      DB_VENDOR: "{{ keycloak_db_vendor }}"
      DB_ADDR: "{{ keycloak_db_addr }}"
      DB_DATABASE: "{{ keycloak_db_database }}"
      DB_USER: "{{ keycloak_db_user }}"
      DB_PASSWORD: "{{ keycloak_db_password }}"
    restart_policy: always
    state: started
