- name: Run PostgreSQL container
  docker_container:
    name: postgres
    image: postgres
    env:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

- name: Run Keycloak container
  docker_container:
    name: keycloak
    image: jboss/keycloak
    env:
      DB_VENDOR: postgres
      DB_ADDR: localhost
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password123
    ports:
      - "8080:8080"
