- name: Wait for PostgreSQL to be ready
  wait_for:
    host: localhost
    port: 5432
    state: started
    delay: 10

- name: Configure Keycloak DB
  docker_container:
    name: keycloak
    image: jboss/keycloak
    env:
      DB_VENDOR: postgres
      DB_ADDR: localhost
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password123
    restart_policy: always
    state: started
