---
- name: Create Docker network
  docker_network:
    name: "{{ docker_network }}"
    state: present

- name: Run PostgreSQL container
  docker_container:
    name: postgres
    image: postgres:13
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    restart_policy: always
    ports:
      - "5432:5432"
    networks:
      - "{{ docker_network }}"

- name: Run Keycloak container
  docker_container:
    name: keycloak
    image: jboss/keycloak:latest
    env:
      DB_VENDOR: "{{ keycloak_db_vendor }}"
      DB_ADDR: "{{ keycloak_db_addr }}"
      DB_DATABASE: "{{ keycloak_db_database }}"
      DB_USER: "{{ keycloak_db_user }}"
      DB_PASSWORD: "{{ keycloak_db_password }}"
    restart_policy: always
    ports:
      - "8080:8080"
    networks:
      - "{{ docker_network }}"

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - "{{ nginx_config_file }}:/etc/nginx/nginx.conf"
      - "{{ nginx_static_dir }}:/usr/share/nginx/html"
    environment:
      KEYCLOAK_URL: "http://keycloak:8080/auth"
      KEYCLOAK_REALM: "{{ keycloak_realm }}"
      CLIENT_ID: "{{ keycloak_client_id }}"
      CLIENT_SECRET: "{{ keycloak_client_secret }}"
    networks:
      - "{{ docker_network }}"