name: Configure

on:
  workflow_run:
    workflows: ["Rollout"]
    types:
      - completed

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH Key and VM IP from Rollout Outputs
        run: |
          VM_IP=$(cat $GITHUB_WORKSPACE/vm_ip.txt)
          echo "VM_IP=${VM_IP}" >> $GITHUB_ENV
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa
          ssh-keyscan -H "${VM_IP}" >> ~/.ssh/known_hosts

      - name: Test SSH Connectivity
        run: |
          ssh -i ~/.ssh/id_ansible_rsa -o StrictHostKeyChecking=no secureadmin@${{ env.VM_IP }} echo "SSH connectivity is working"

      - name: Copy Ansible Playbook and Roles
        run: |
          scp -i ~/.ssh/id_ansible_rsa -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/ansible secureadmin@${{ env.VM_IP }}:~/ansible

      - name: Run Ansible Playbook on Remote VM
        run: |
          ssh -i ~/.ssh/id_ansible_rsa -o StrictHostKeyChecking=no secureadmin@${{ env.VM_IP }} << 'EOF'
            source ~/ansible-env/bin/activate
            ansible -i ~/ansible/hosts webserver -m ping -vvv
            ansible-playbook -vvv -i ~/ansible/hosts ~/ansible/playbook.yml
          EOF
