# .github/workflows/configure.yml
name: Configure Resources
# manuel via interface GitHub Actions
on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Refresh Terraform state
        run: terraform refresh
        working-directory: terraform/
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: terraform/

      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
