name: Configure Resources
on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Assure que la clé SSH est disponible pour Ansible
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Create SSH key file
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          echo "${ANSIBLE_SSH_PRIVATE_KEY}" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa
          
      # Récupération de l'IP depuis une sortie Terraform ou une variable d'environnement
      - name: Get VM IP from Terraform Output
        id: get_ip
        run: |
          # Supposons que l'IP est stockée dans un fichier Terraform output
          VM_IP=$(terraform output -raw public_ip_address)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
        working-directory: terraform/
        
      - name: Debug VM IP
        run: echo "VM IP is $VM_IP"

      # Crée l'inventaire statique pour Ansible
      - name: Create Static Inventory with VM IP
        run: |
          echo "[webserver]" > $GITHUB_WORKSPACE/ansible/hosts
          echo "$VM_IP ansible_user=secureadmin ansible_ssh_private_key_file=~/.ssh/id_ansible_rsa" >> $GITHUB_WORKSPACE/ansible/hosts
        working-directory: ansible/

      - name: Debug the created inventory
        run: cat $GITHUB_WORKSPACE/ansible/hosts

      # Exécute le playbook Ansible
      - name: Run Ansible Playbook with Static Inventory
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: $GITHUB_WORKSPACE/ansible/hosts
