# .github/workflows/configure.yml

name: Configure Resources

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/

      # Récupérer l'adresse IP de la VM et l'enregistrer dans un fichier JSON
      - name: Save VM IP address to JSON file
        run: terraform output -json > ansible/vm_ip.json
        working-directory: terraform/

      # Générer l'inventaire dynamique pour Ansible
      - name: Generate dynamic inventory
        run: |
          python3 ansible/dynamic_inventory.py

      # Exécuter le playbook Ansible avec l'inventaire dynamique
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: ansible/vm_inventory.json  # Chemin du fichier généré par dynamic_inventory.py
