# .github/workflows/configure.yml

name: Configure Resources
# Manuel via interface GitHub Actions
on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/

      # Récupérer l'adresse IP de la VM et l'enregistrer dans un fichier JSON
      - name: Save VM IP address to JSON file
        run: terraform output -json > vm_ip.json
        working-directory: terraform/

      # Copier l'adresse IP de la VM dans le répertoire ansible
      - name: Copy IP JSON file
        run: cp terraform/vm_ip.json ansible/vm_ip.json

      # Configurer Ansible avec l'inventaire dynamique
      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml

      # Exécuter le playbook Ansible
      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          inventory: ansible/dynamic_inventory.py  # Utilisation de l'inventaire dynamique
          playbook: ansible/playbook.yml
