name: Rollout
on:
  push:
    branches:
      - main
jobs:
  rollout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform/

      - name: Authenticate with Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Import existing resource group
        run: terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/my-first-terraform-RG
        working-directory: terraform/

      - name: Import Virtual Network
        run: terraform import azurerm_virtual_network.my_terraform_network /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/my-first-terraform-RG/providers/Microsoft.Network/virtualNetworks/my-first-terraform-network
        working-directory: terraform/

      - name: Import Public IP Address
        run: terraform import azurerm_public_ip.my_terraform_public_ip /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/my-first-terraform-RG/providers/Microsoft.Network/publicIPAddresses/my-first-terraform-PublicIP
        working-directory: terraform/

      - name: Import Network Security Group
        run: terraform import azurerm_network_security_group.my_terraform_nsg /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/my-first-terraform-RG/providers/Microsoft.Network/networkSecurityGroups/my-first-terraform-NSG
        working-directory: terraform/  

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform/

      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
