name: Rollout
on:
  push:
    branches:
      - main

jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate with Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Initialize Terraform with Backend
        run: terraform init -backend-config="${GITHUB_WORKSPACE}/terraform/backend.tfvars"
        working-directory: terraform/

      - name: Apply Terraform to create VM
        run: terraform apply -auto-approve
        working-directory: terraform/
        timeout-minutes: 30

      - name: Get VM IP and private key from Terraform output
        id: get_outputs
        run: |
          VM_IP=$(terraform output -raw VM_IP | grep -oP '(\d{1,3}\.){3}\d{1,3}' | head -n 1)
          PRIVATE_KEY=$(terraform output -raw private_key)
          echo "$VM_IP" > $GITHUB_WORKSPACE/vm_ip.txt
          echo "$PRIVATE_KEY" > $GITHUB_WORKSPACE/id_ansible_rsa
        working-directory: terraform/

      - name: Export VM IP to environment file
        run: |
          VM_IP=$(cat $GITHUB_WORKSPACE/vm_ip.txt)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
          echo "VM_IP is $VM_IP"  # This line for debugging purposes

      - name: Prepare SSH Directory
        run: |
          mkdir -p ~/.ssh
          echo "$(cat $GITHUB_WORKSPACE/id_ansible_rsa)" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Update known_hosts with VM IP
        run: |
          VM_IP=$(cat $GITHUB_WORKSPACE/vm_ip.txt)
          ssh-keygen -R "$VM_IP" || true
          ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
        shell: bash

      - name: Delay for SSH configuration propagation
        run: sleep 5

      - name: Test SSH Connectivity with SSH command
        run: ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt) echo "SSH connectivity is working"

      - name: Setup Python 2.7 and Ansible 2.9.0 on VM
        run: |
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt) << 'EOF'
            set -e
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt remove --purge python3-venv ansible -y || true
            sudo apt autoremove -y
            sudo apt install -y python2.7 python-pip
            pip install ansible==2.9.0
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            ansible-playbook --version
          EOF

      - name: Create Ansible Inventory on VM
        run: |
          VM_IP=$(cat $GITHUB_WORKSPACE/vm_ip.txt)
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa secureadmin@$VM_IP << 'EOF'
            mkdir -p ~/ansible
            echo "[webserver]" > ~/ansible/hosts
            echo "$VM_IP ansible_user=secureadmin" >> ~/ansible/hosts
          EOF

      - name: Copy Ansible Playbook and Roles
        run: |
          scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa -r $GITHUB_WORKSPACE/ansible/playbook.yml secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt):~/ansible/
          scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa -r $GITHUB_WORKSPACE/ansible/roles secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt):~/ansible/

      - name: Check Files on VM
        run: |
          ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt) << 'EOF'
            ls -l ~/ansible
            cat ~/ansible/hosts
            cat ~/ansible/playbook.yml
          EOF

      - name: Run Ansible Playbook
        run: ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ~/.ssh/id_ansible_rsa secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt) ansible-playbook ~/ansible/playbook.yml
