name: Rollout
on:
  push:
    branches:
      - main

jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate with Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Initialize Terraform with Backend
        run: terraform init -backend-config="${GITHUB_WORKSPACE}/terraform/backend.tfvars"
        working-directory: terraform/

      - name: Apply Terraform to create VM
        run: terraform apply -auto-approve
        working-directory: terraform/

      - name: Get VM IP from Terraform output
        id: get_ip
        run: |
          # Extraire l'IP sans guillemets ni autres caractères indésirables
          VM_IP=$(terraform output -raw public_ip_address | awk -F'"' '{print $2}')
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Create SSH key file
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          echo "${ANSIBLE_SSH_PRIVATE_KEY}" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa

      - name: Create Static Inventory with VM IP
        run: |
          echo "[webserver]" > $GITHUB_WORKSPACE/ansible/hosts
          echo "${{ env.VM_IP }} ansible_user=secureadmin ansible_ssh_private_key_file=~/.ssh/id_ansible_rsa" >> $GITHUB_WORKSPACE/ansible/hosts

      - name: Debug VM IP (print it)
        run: echo "VM IP is ${{ env.VM_IP }}"

      - name: Debug the created inventory
        run: cat $GITHUB_WORKSPACE/ansible/hosts

      - name: Run Ansible Playbook with Static Inventory
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: $GITHUB_WORKSPACE/ansible/hosts