name: Rollout
on:
  push:
    branches:
      - main

jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Authenticate with Azure
      - name: Authenticate with Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        working-directory: terraform/

      # Step 4: Initialize Terraform with Backend configuration
      - name: Initialize Terraform with Backend
        run: terraform init -backend-config="${GITHUB_WORKSPACE}/terraform/backend.tfvars"
        working-directory: terraform/

      # Step 5: Apply Terraform to create VM
      - name: Apply Terraform to create VM
        run: terraform apply -auto-approve
        working-directory: terraform/

      # Step 6: Get VM IP from Terraform output
      - name: Get VM IP from Terraform output
        id: get_ip
        run: |
          # Extract the public IP address from Terraform output
          VM_IP=$(terraform output -raw public_ip_address | awk -F'"' '{print $2}')
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
        working-directory: terraform/

      # Step 7: Create SSH directory
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      # Step 8: Create SSH key file for Ansible connection
      - name: Create SSH key file
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          echo "${ANSIBLE_SSH_PRIVATE_KEY}" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa

      # Step 9: Debug VM IP - Show the IP value
      - name: Debug VM IP
        run: echo "VM IP is $VM_IP"

      # Step 10: Create Static Inventory with VM IP - Dynamically generate Ansible inventory
      - name: Create Static Inventory with VM IP
        run: |
          # Assurez-vous que le chemin vers 'hosts' est correct avec $GITHUB_WORKSPACE
          echo "[webserver]" > $GITHUB_WORKSPACE/ansible/hosts
          echo "$VM_IP ansible_user=secureadmin ansible_ssh_private_key_file=~/.ssh/id_ansible_rsa" >> $GITHUB_WORKSPACE/ansible/hosts
        env:
          VM_IP: ${{ env.VM_IP }}
        working-directory: ansible/

      # Step 11: Debug the created inventory - Print out the contents of the Ansible inventory file
      - name: Debug the created inventory
        run: cat $GITHUB_WORKSPACE/ansible/hosts

      # Step 12: Run Ansible Playbook with Static Inventory
      - name: Run Ansible Playbook with Static Inventory
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: $GITHUB_WORKSPACE/ansible/hosts
