name: Rollout
on:
  push:
    branches:
      - main

jobs:
  rollout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate with Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
        working-directory: terraform/

      - name: Initialize Terraform with Backend
        run: terraform init -backend-config="${GITHUB_WORKSPACE}/terraform/backend.tfvars"
        working-directory: terraform/

      - name: Apply Terraform to create VM
        run: terraform apply -auto-approve
        working-directory: terraform/

      - name: Get VM IP from Terraform output
        id: get_ip
        run: |
          VM_IP=$(terraform output -raw VM_IP | grep -oP '(\d{1,3}\.){3}\d{1,3}' | head -n 1)
          echo "Extracted VM_IP: $VM_IP"
          echo $VM_IP > $GITHUB_WORKSPACE/vm_ip.txt
        working-directory: terraform/

      - name: Export VM IP to environment file
        run: echo "VM_IP=$(cat $GITHUB_WORKSPACE/vm_ip.txt)" >> $GITHUB_ENV

      - name: Debug VM IP
        run: echo "VM IP is $(cat $GITHUB_WORKSPACE/vm_ip.txt)"

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Create SSH key file
        env:
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
        run: |
          echo "${ANSIBLE_SSH_PRIVATE_KEY}" > ~/.ssh/id_ansible_rsa
          chmod 600 ~/.ssh/id_ansible_rsa

      - name: Convert SSH Key to OpenSSH format
        run: ssh-keygen -p -m PEM -f ~/.ssh/id_ansible_rsa -N ""

      - name: Test SSH Connectivity
        run: ssh -i ~/.ssh/id_ansible_rsa -o StrictHostKeyChecking=no secureadmin@$(cat $GITHUB_WORKSPACE/vm_ip.txt) echo "SSH connectivity is working"

      - name: Create Static Inventory with VM IP
        run: |
          echo "[webserver]" > $GITHUB_WORKSPACE/ansible/hosts
          IP_ADDRESS=$(cat $GITHUB_WORKSPACE/vm_ip.txt | head -n 1)
          echo "$IP_ADDRESS ansible_user=secureadmin ansible_ssh_private_key_file=~/.ssh/id_ansible_rsa" >> $GITHUB_WORKSPACE/ansible/hosts

      - name: Debug the created inventory
        run: cat $GITHUB_WORKSPACE/ansible/hosts

      - name: Run Ansible Playbook with Static Inventory
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbook.yml
          inventory: $GITHUB_WORKSPACE/ansible/hosts
        env:
          VM_IP: ${{ env.VM_IP }}
